### ISSUE TITLE
Very old version of the website is still alive in https://json-schema.github.io/json-schema/

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#186]
Today I found that a very old version of the website is still alive in https://json-schema.github.io/json-schema/

What is the recommended course of action in this case?

**Comment by Julian** [comment]
That comes from https://github.com/json-schema/json-schema and is live still because we don't have full owner access to the old `json-schema` account on GitHub. That's come up a few times (whether we want to now go get it), but for that page specifically I personally wouldn't worry about it, as in 10 years I don't think I've ever seen any user find or mention it.
