### ISSUE TITLE
Search box of header misplaced for certain mobiles 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#398]
#### Describe the bug
The search box of the header is misplaced too much to the left side for certain mobiles

Current:
<img width="480" alt="Screenshot 2024-03-01 at 10 41 23" src="https://github.com/json-schema-org/website/assets/40007659/ce7cee6f-6bff-441e-b752-6a58e9718726">

Desired:
<img width="316" alt="Screenshot 2024-03-01 at 10 45 09" src="https://github.com/json-schema-org/website/assets/40007659/9628a599-7b6f-48b7-9631-2a530d288413">

**Comment by kx412764776** [comment]
@benjagm Should I pick up this issue?

**Comment by benjagm** [comment]
Please do. @kx412764776

**Comment by kx412764776** [comment]
@benjagm On my device, the search box doesn't look quite the same as yours. It looks like this.

![image](https://github.com/json-schema-org/website/assets/117196993/ae9c1e6c-516b-4402-90fa-322262e96cf8)

Do you expect the search text to be displayed in the search box?

**Comment by benjagm** [comment]
> On my device, the search box doesn't look quite the same as yours

I am using the desktop browser in dev mode to test it in a Pixel 7 device. What is the device are you testing?

**Comment by kx412764776** [comment]
@benjagm It's probably because of my chrome settings. Now the search box looks like this on different mobiles.

![image](https://github.com/json-schema-org/website/assets/117196993/a9101809-bda4-4544-9823-8494abe4cc3e)

![image](https://github.com/json-schema-org/website/assets/117196993/d75d0387-ec83-4697-a372-06eb9889ff33)

![image](https://github.com/json-schema-org/website/assets/117196993/a7915002-afad-4c29-9e92-f8947e59b46d)

**Comment by kx412764776** [comment]
@benjagm I have committed it but since I have already created a PR #400 in the morning and changed the introduction of the tools and obsolete tools pages, so those changes are now in a PR, can you review it? 
If the first changes can't be merged, I could create a new PR.
