### ISSUE TITLE
🐛 Bug: Problem with workflows/welcome-first-time-contrib.yml

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#516]
### Describe the bug

We are getting errors in the execution of the workflow welcome-first-time-contrib.yml. See details here:
https://github.com/json-schema-org/website/actions/runs/8241136701/job/22537807615?pr=515

### Steps To Reproduce

This is happening as part of the PR creation/update process.

### Expected Behavior

I think this should happen.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Thanks Satya. All yours!

**Comment by aialok** [comment]
@satyam-x10  The workflow is failing because the `GITHUB_TOKEN` does not have write access. You can resolve this issue by using the `pull_request_target` event, as it grants both read and write permissions to the `GITHUB_TOKEN`. 
You can learn more about this (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).

**Comment by satyam-x10** [comment]
> [@satyam-x10](https://github.com/satyam-x10) The workflow is failing because the `GITHUB_TOKEN` does not have write access. You can resolve this issue by using the `pull_request_target` event, as it grants both read and write permissions to the `GITHUB_TOKEN`. You can learn more about this (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).

thank you so much for the help

**Comment by satyam-x10** [comment]
@benjagm  i have raise  the  PR for this issue. Kindly review it . Thanks
