### ISSUE TITLE
Roll-out plan for the new Website

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#53]
As soon as #45 is completed and #44 merged we should start the new website roll-out plan. This has to be an MVP approach to have it released ASAP and being able to iterate.

The action plan goes as follow:
- [x] Provide planning dates.
- [x] Development completed.
- [x] Current site content freeze.
- [x] Validate no broken links
- [x] Validate no missing content
- [x] Site setup on Cloudflare
- [x] Disable old site pipelines
- [x] CI/CD setup. Github Actions
- [x] Release
- [x] Comms

The dates goes as follows:

**1. Close the Landing design:** Friday, May 12th
**2. Landing Development:** From May to Sept 17th
**3. Current site content freeze.**  Sept 25th to Oct 1st
**4. Last content checks:** Sept 25th to Oct 1st
**5. Site setup:** Sept 25th to Oct 1st
**6. CI/CD setup:** Sept 25th to Oct 1st
**7. Disable old site pipelines:** Sept 25th to Oct 1st
**8. Release:** Oct 2nd 
**9. Comms:** Oct 2nd

**Comment by Julian** [comment]
Very minor feedback I see, likely all of which can be ignored/deferred if need be -- obviously feel free to hide this comment / move wherever if here isn't a good spot:


White / inverted links also need at least *some* hover CSS or something, because it's quite unobvious that they're links, e.g.:

<img width="917" alt="Screenshot 2023-09-12 at 10 05 18" src="https://github.com/json-schema-org/website/assets/329822/98a888c8-cdd0-4ce2-93e6-0e86714441c6">

The same sort of applies to the hero buttons to me, a button fill would be nice I suspect, right now all that indicates they're buttons is the hand cursor switch:

<img width="917" alt="Screenshot 2023-09-12 at 10 06 04" src="https://github.com/json-schema-org/website/assets/329822/3dd88f80-f111-4b3f-8ef0-29bec9f81896">

At least on dark themed browsers, the favicon is a bit wonky:

<img width="107" alt="Screenshot 2023-09-12 at 10 08 05" src="https://github.com/json-schema-org/website/assets/329822/d31c144b-ab9a-48ac-be27-955eb7465ea1">

In the hero text:

<img width="917" alt="Screenshot 2023-09-12 at 10 09 00" src="https://github.com/json-schema-org/website/assets/329822/fc48f3a8-37c3-4d02-8fab-be0249c03071">

I'm definitely one to usually be careful with claims but here I feel like the caution is probably unneeded, it seems pretty safe to say JSON is the most used format for exchanging data.

The grammar is slightly off there too I think, it seems like it should be "... that allows *for* JSON ..." or slightly less awkward might be "enables", not sure.

The "learn JSON Schema" button:

<img width="917" alt="Screenshot 2023-09-12 at 10 14 24" src="https://github.com/json-schema-org/website/assets/329822/0bd28300-c43c-488b-9cde-84e9b1eabd8b">

seems like the sort of thing an absolute beginner will click, but the first prominent section on that page:

<img width="917" alt="Screenshot 2023-09-12 at 10 15 17" src="https://github.com/json-schema-org/website/assets/329822/52342180-5d95-4f51-b498-c5e533cb5f14">

deals with JSON Schema History, which is sort of a weird thing to start with for a beginner IMHO. Perhaps to me would be a bit better to link directly to the "Getting Started" page instead.

The homepage uses the word "trusted" in:

> Discover trusted JSON Schema tooling to help your organization leverage the benefits of JSON Schema.

But the implementation page (and common sense :) says:

> Listing does not signify a recommendation or endorsement of any kind.

I'd possibly try to reword to not use a word like "trusted".

Also:

<img width="917" alt="Screenshot 2023-09-12 at 10 17 40" src="https://github.com/json-schema-org/website/assets/329822/b313ae60-5721-48b2-a6d9-cdf614198e58">

Even I don't know what number that 60 million installs refers to! At very least it could use a footnote, but it seems slightly misleading / likely to make someone think JSON Schema is a piece of software. Perhaps, assuming it refers to aggregate installs of *tools* in the ecosystem, it should just have that extra word or something (*and* the footnote IMHO).

Also, the headings here look slightly weird to me (too small? or not enough spacing?):
<img width="1192" alt="Screenshot 2023-09-12 at 10 19 09" src="https://github.com/json-schema-org/website/assets/329822/f2cc168c-892a-44b4-ad97-594a0de4b2dc">

I'd also replace the "Welcome to our Blog" heading which I'm guessing might be from the template, to something more like "The JSON Schema Blog" or "Official Blog" or something.

The typography on the calendar looks off to me too personally:

<img width="432" alt="Screenshot 2023-09-12 at 10 20 23" src="https://github.com/json-schema-org/website/assets/329822/912875d3-02fd-4057-8b49-119da2e23234">

it doesn't quite look like a "cohesive widget" per se, the body text looks a bit large, dunno.

There's also an extra "the" here:

<img width="658" alt="Screenshot 2023-09-12 at 10 21 35" src="https://github.com/json-schema-org/website/assets/329822/17068163-7c52-4e63-8544-f0d07f426043">


The Orbit logo somehow looks *blurry* to me... especially next to the tack-sharp Slack logo. Not sure if that's really the source image that's blurry or if some funny compression artifacts are happening. Screenshot, though might be hard to tell:

<img width="917" alt="Screenshot 2023-09-12 at 10 03 43" src="https://github.com/json-schema-org/website/assets/329822/aeeb5fa0-e9a5-4c3b-a8f4-66ae11ffb6aa">

Also, the line wrapping on the paragraph above is a bit weird:

<img width="917" alt="Screenshot 2023-09-12 at 10 04 30" src="https://github.com/json-schema-org/website/assets/329822/19d2265c-c17a-4447-9e99-fbab7bccbaa9">

and to me there is a tiny bit too much padding between there and the "Sponsors" section above it.

I guess finally (at least for the homepage which is all I flipped through for now), the Code of Conduct links to the OpenJS CoC rather than ours -- that whole footer looks like canned OpenJS footer, but that's a bit confusing. It seems it should link to ours to me.

**Comment by benjagm** [comment]
This is great feedback @Julian and makes lot of sense. As soon as we are done with the content migration/validation I'll try to implement most for the launch.

**Comment by benjagm** [comment]
> I propose we do the following to sunset these repos.
Sounds great to me.

**Comment by gregsdennis** [comment]
> Also, the headings here look slightly weird to me (too small? or not enough spacing?): - @Julian 

They're properly space, but they're left-aligned.  The middle should be centered, and the right needs to be right aligned.

**Comment by gregsdennis** [comment]
> Also, the line wrapping on the paragraph above is a bit weird: - @Julian 

I don't see this wrapping in desktop.  Are you on mobile?
<img width="419" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/db90c2be-7ffe-4c69-80d2-f71004de81de">

**Comment by benjagm** [comment]
Closed as completed.
