### ISSUE TITLE
🐛 Bug:  @cfworker/json-schema is not showing the bowtie badges in the details modal window

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#999]
### Describe the bug

`@cfworker/json-schema` is not showing the bowtie badges in the details modal window

<img width="877" alt="Screenshot 2024-10-04 at 09 06 48" src="https://github.com/user-attachments/assets/45e1fabe-0b95-4b8f-b6bd-f7491a8d79b4">

### Steps To Reproduce

Go to tooling page and click in cfworker/json-schema to show the details.

### Expected Behavior

Show the bowtie fields.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by RonakSurana-2001** [comment]
I am not able to understand can you explain more clearly

**Comment by Mohith1490** [comment]
Hey @benjagm according to above details  "js-json-schema" should look like a badge, like above one right.

**Comment by DarhkVoyd** [comment]
Hi everyone,

Thanks for your interest in this issue! I wanted to let you know that I’m currently working on resolving this. Since this has become a bit more complex than just adding badges and it is no longer a Hacktoberfest issue, I'll be handling the fix. I'll update the label to reflect this.

Please feel free to reach out if you have any questions or need clarification.
